name: Package - Windows
on:
  workflow_dispatch:
    #Empty for now - no parameters yet
  workflow_call:
    #Empty for now - no parameters yet

jobs:
  windows:
    name: Windows
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            zip
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-scons
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-physfs

      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Configure and Build
        run: scons -j`nproc` sdl2=1 sdlmixer=1

      - name: Package
        run: ./contrib/packaging/windows/build_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: '*.zip'
