name: Package - Linux
on:
  workflow_dispatch:
    #Empty for now - no parameters yet
  workflow_call:
    #Empty for now - no parameters yet

jobs:
  ubuntu2004:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Update Package Database
        run: sudo apt-get update

      - name: Install AppImage Requirements
        run: sudo apt-get install -y fuse libfuse2

      - name: Install Download Tools
        run: sudo apt-get install -y wget curl

      - name: Install AppImage Stuff
        run: |
          mkdir ~/Applications
          curl -s -L --output ~/Applications/linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod 0755 ~/Applications/linuxdeploy-x86_64.AppImage

      - name: Install gcc and g++
        run: |
          sudo apt install -y software-properties-common
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt install -y gcc-11 g++-11

      - name: Install Python and SCons
        run: |
          sudo apt install -y python3
          mkdir ~/venv
          python3 -m venv ~/venv
          . ~/venv/bin/activate && pip install Scons==4.0.1

      - name: Install dxx-rebirth Dependencies
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libphysfs-dev libpng-dev

      - name: Configure and Build
        run: . ~/venv/bin/activate && scons -j`nproc` opengl=1 sdl2=1 sdlmixer=1
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Package AppImage d1x-rebirth
        env:
          OUTPUT: D1X-Rebirth-u2004-x86_64.AppImage
        run: |
          ~/Applications/linuxdeploy-x86_64.AppImage \
            -oappimage \
            --appdir="d1x-rebirth.appdir" \
            --executable="build/d1x-rebirth/d1x-rebirth" \
            --desktop-file="d1x-rebirth/d1x-rebirth.desktop" \
            --icon-file="d1x-rebirth/d1x-rebirth.png"

      - name: Package AppImage d2x-rebirth
        env:
          OUTPUT: D2X-Rebirth-u2004-x86_64.AppImage
        run: |
          ~/Applications/linuxdeploy-x86_64.AppImage \
            -oappimage \
            --appdir="d2x-rebirth.appdir" \
            --executable="build/d2x-rebirth/d2x-rebirth" \
            --desktop-file="d2x-rebirth/d2x-rebirth.desktop" \
            --icon-file="d2x-rebirth/d2x-rebirth.png"

      - name: Zip AppImages
        run: zip -r -X DXX-Rebirth-ubuntu-20.04.zip . -i '*.AppImage'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-ubuntu-20.04
          path: '*.zip'



  ubuntu2204:
    name: Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Update Package Database
        run: sudo apt-get update

      - name: Install AppImage Requirements
        run: sudo apt-get install -y libfuse2

      - name: Install Download Tools
        run: sudo apt-get install -y wget curl

      - name: Install AppImage Stuff
        run: |
          mkdir ~/Applications
          curl -s -L --output ~/Applications/linuxdeploy-x86_64.AppImage https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          chmod 0755 ~/Applications/linuxdeploy-x86_64.AppImage

      - name: Install gcc and g++
        run: sudo apt install -y gcc-11 g++-11

      - name: Install Python and SCons
        run: sudo apt install -y python3 scons

      - name: Install dxx-rebirth Dependencies
        run: sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libphysfs-dev libpng-dev

      - name: Configure and Build
        run: scons -j`nproc` opengl=1 sdl2=1 sdlmixer=1
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Package AppImage d1x-rebirth
        env:
          OUTPUT: D1X-Rebirth-u2204-x86_64.AppImage
        run: |
          ~/Applications/linuxdeploy-x86_64.AppImage \
            -oappimage \
            --appdir="d1x-rebirth.appdir" \
            --executable="build/d1x-rebirth/d1x-rebirth" \
            --desktop-file="d1x-rebirth/d1x-rebirth.desktop" \
            --icon-file="d1x-rebirth/d1x-rebirth.png"

      - name: Package AppImage d2x-rebirth
        env:
          OUTPUT: D2X-Rebirth-u2204-x86_64.AppImage
        run: |
          ~/Applications/linuxdeploy-x86_64.AppImage \
            -oappimage \
            --appdir="d2x-rebirth.appdir" \
            --executable="build/d2x-rebirth/d2x-rebirth" \
            --desktop-file="d2x-rebirth/d2x-rebirth.desktop" \
            --icon-file="d2x-rebirth/d2x-rebirth.png"

      - name: Zip AppImages
        run: zip -r -X DXX-Rebirth-ubuntu-22.04.zip . -i '*.AppImage'

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage-ubuntu-22.04
          path: '*.zip'
