name: Package - Linux
on:
  workflow_dispatch:
    #Empty for now - no parameters yet
  workflow_call:
    #Empty for now - no parameters yet

jobs:
  package:
    name: GCC 11
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Update Package Database
        run: sudo apt-get update

      - name: Install Build Dependencies
        run: sudo apt install -y gcc-11 g++-11 python3 scons

      - name: Install dxx-rebirth Dependencies
        run: sudo apt install -y libsdl1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libphysfs-dev libpng-dev

      - name: Configure and Build
        run: scons -j`nproc`
        env:
          CC: gcc-11
          CXX: g++-11

      - name: Install AppImage Requirements
        run: sudo apt-get install -y libfuse2 wget curl

      - name: Package
        run: ./contrib/packaging/linux/build_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-appimage
          path: '*.zip'
