name: Packages

on:
  #push:
  #  branches: [ master ]

  #pull_request:
  #  branches: [ master ]

  workflow_dispatch:

jobs:
  linux:
    name: Linux AppImages
    runs-on: ubuntu-20.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y scons libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libphysfs-dev
          
      - name: Configure and build
        run: scons -j`nproc` opengl=1 sdl2=1 sdlmixer=1
      
      - name: Package AppImage
        run: ./contrib/packaging/linux/build_package.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: '*.AppImage'
          
  macos:
    name: macOS Apps
    runs-on: macos-10.15
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
       
      - name: Prepare environment
        run: export MACOSX_DEPLOYMENT_TARGET=10.14
        
      - name: Install dependencies
        run: |
          brew install scons sdl2 sdl2_image sdl2_mixer physfs pkg-config
          
      - name: Configure and build
        run: scons -j2 opengl=1 sdl2=1 sdlmixer=1 macos_add_frameworks=0
      
      - name: Package
        run: ./contrib/packaging/macos/build_package.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: '*.zip'          

  windows:
    name: Windows
    runs-on: windows-2019
    
    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            zip
            base-devel 
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-scons
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_image
            mingw-w64-x86_64-SDL2_mixer
            mingw-w64-x86_64-physfs
        
      - name: Clone repository
        uses: actions/checkout@v3
              
      - name: Configure and build
        run: scons -j2 sdl2=1 sdlmixer=1
      
      - name: Package
        run: ./contrib/packaging/windows/build_package.sh
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows
          path: '*.zip'
          
