name: Package All and Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag Name (new or existing)
        required: true
        type: string
      prerelease:
        description: Pre-release?
        default: true
        type: boolean

jobs:
  linux:
    name: Package Linux
    uses: ./.github/workflows/package-linux.yml

  windows:
    name: Package Windows
    uses: ./.github/workflows/package-windows.yml

  macos:
    name: Package MacOS
    uses: ./.github/workflows/package-macos.yml

  release:
    name: Release
    needs:
      - linux
      - windows
      - macos
    uses: ./.github/workflows/release.yml
    with:
      tag_name: ${{ inputs.tag_name }}
      prerelease: ${{ inputs.prerelease }}
